name: Clean branches

on:
  schedule:
    - cron: "* * * 1 0"
  workflow_dispatch:

jobs:
  clean_branches:
      name: clean_branches
      runs-on: ubuntu-latest
      steps:
        - name: Install SSH key
          uses: shimataro/ssh-key-action@v2
          with:
            key: ${{ secrets.SSH }}
            known_hosts: ${{ secrets.KNOWN_HOSTS }}

        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0

        - name: Clean branches
          run: bash ./scripts/check_branches.sh
